# ETL

In [1]:
# Se importa la biblioteca 'pandas' para manipulación y análisis de datos en tablas.
import pandas as pd
# Se importa la biblioteca 'sqlalchemy' para conectar y gestionar bases de datos.
import sqlalchemy as db
# Se importa la función 'text' de sqlalchemy para construir consultas SQL.
from sqlalchemy import text

In [3]:
# Crear un motor de BD
engine = db.create_engine("mysql://root:root@127.0.0.1:3310/db_movies_netflix_transact")

# Crear la conexion
conn = engine.connect()

# Cargar la dimension Movie

In [4]:
query = """
SELECT 
    movie.movieID as movieID, movie.movieTitle as title, movie.releaseDate as releaseDate, 
    gender.name as gender , person.name as participantName, participant.participantRole as roleparticipant 
FROM movie 
INNER JOIN participant 
ON movie.movieID=participant.movieID
INNER JOIN person
ON person.personID = participant.personID
INNER JOIN movie_gender 
ON movie.movieID = movie_gender.movieID
INNER JOIN gender 
ON movie_gender.genderID = gender.genderID
"""

In [6]:
# con pandas voy a leer los resultados del query
movies_data = pd.read_sql(query, con=conn)

movies_data["movieID"]= movies_data["movieID"].astype("int")

movies_data

,movieID,title,releaseDate,gender,participantName,roleparticipant
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director

In [14]:
# Cargar la informacion de premios
movies_award=pd.read_csv("./data/Awards_movie.csv")

#convertir el MovieID a int
movies_award["movieID"]= movies_award["movieID"].astype("int")

#renombrar los campos
movies_award.rename(columns={"Aware":"Award"}, inplace=True)

movies_award

    movieID  IdAward   Award
0  80210920        0   Oscar
1  81157374        1  Grammy
2  80192187        2   Oscar

In [13]:
movies_award

    movieID  IdAward   Aware
0  80210920        0   Oscar
1  81157374        1  Grammy
2  80192187        2   Oscar