# ETL

In [1]:
# Se importa la biblioteca 'pandas' para manipulación y análisis de datos en tablas.
import pandas as pd
# Se importa la biblioteca 'sqlalchemy' para conectar y gestionar bases de datos.
import sqlalchemy as db
# Se importa la función 'text' de sqlalchemy para construir consultas SQL.
from sqlalchemy import text

In [3]:
# Crear un motor de BD
engine = db.create_engine("mysql://root:root@127.0.0.1:3310/db_movies_netflix_transact")

# Crear la conexion
conn = engine.connect()

# Cargar la dimension Movie

In [4]:
query = """
SELECT 
    movie.movieID as movieID, movie.movieTitle as title, movie.releaseDate as releaseDate, 
    gender.name as gender , person.name as participantName, participant.participantRole as roleparticipant 
FROM movie 
INNER JOIN participant 
ON movie.movieID=participant.movieID
INNER JOIN person
ON person.personID = participant.personID
INNER JOIN movie_gender 
ON movie.movieID = movie_gender.movieID
INNER JOIN gender 
ON movie_gender.genderID = gender.genderID
"""

In [6]:
# con pandas voy a leer los resultados del query
movies_data = pd.read_sql(query, con=conn)

movies_data["movieID"]= movies_data["movieID"].astype("int")

movies_data

,movieID,title,releaseDate,gender,participantName,roleparticipant
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director

In [14]:
# Cargar la informacion de premios
movies_award=pd.read_csv("./data/Awards_movie.csv")

#convertir el MovieID a int
movies_award["movieID"]= movies_award["movieID"].astype("int")

#renombrar los campos
movies_award.rename(columns={"Aware":"Award"}, inplace=True)

movies_award

    movieID  IdAward   Award
0  80210920        0   Oscar
1  81157374        1  Grammy
2  80192187        2   Oscar

In [16]:
# Unir las dos tablas o fuentes de datos
movie_data = pd.merge(movies_data, movies_award,
                left_on= 'movieID',
                right_on='movieID'
)

# Transformaciones Finales
movie_data = movie_data.rename(columns={'releaseDate': 'releaseMovie', 'Award': 'awardMovie'}) # Similar a poner implace true

#Elimnar un campo

movie_data = movie_data.drop(columns=['IdAward'])

movie_data

,movieID,title,releaseMovie,gender,participantName,roleparticipant,awardMovie
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,Grammy

In [17]:
# Cargar la tabla

# Crear el motor y conexiones a de_netflix
# Crear un motor de BD
engine_dw = db.create_engine("mysql://root:root@127.0.0.1:3310/dw_netflix")

# Crear la conexion
conn_dw = engine_dw.connect()

In [18]:
# Insertamos los valores
movie_data.to_sql('dimMovie', conn_dw, if_exists='append', index=False)

3

# Dimension Users

In [21]:
# cargar la informacion Usuario

users = pd.read_csv('./data/users.csv', sep = '|')

users.head()

    idUser     username    country subscription
0  1002331      user123        USA      Premium
1  1002332  gamerGirl97     Canada        Basic
2  1002333   techMaster         UK      Premium
3  1002334    soccerFan     Brazil        Basic
4  1002335    travelBug  Australia      Premium

In [24]:
# renombrar unas columnas
users = users.rename(columns={'idUser':'userID'})

users.head()

    userID     username    country subscription
0  1002331      user123        USA      Premium
1  1002332  gamerGirl97     Canada        Basic
2  1002333   techMaster         UK      Premium
3  1002334    soccerFan     Brazil        Basic
4  1002335    travelBug  Australia      Premium

In [ ]:
# Cargar al dw
users.to_sql('dimUser', conn_dw, if_exists='append', index=False)

20